import { Inter } from "next/font/google";
import "./globals.css";
import CommanLayout from "./components/comman-layout";
import SessionWrapper from "./components/sessionWrapper";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SessionWrapper>

      <body className={inter.className}>
         <CommanLayout>
        {children}
         </CommanLayout>
        </body>
      </SessionWrapper>
    </html>
  );
}
